### ISSUE TITLE
Implications of new JSDoc rules

### ISSUE THREAD

**Issue by mcmire** [MetaMask/eslint-config#215]
It looks like the new JSDoc has some implications which I feel may be undesirable. There are two issues I've noticed:

* JSDoc is required in test files. When writing tests it may be useful to make functions that you can use inside of tests to encapsulate and reuse setup code. I don't feel that it is useful, however, to have these functions documented. When writing JSDoc, I imagine that one day this JSDoc would be formatted and published on a GitHub Pages site or something. I don't imagine, though, that we would ever do that for test files.
* Presently, JSDoc is also required for *all* functions/classes/etc. However, I am wondering whether it would be more useful to require JSDoc *only* for things that are exported from a module. Again, going back to imagining how we might publish the JSDoc we write one day, it seems like we would not need to publish documentation for things that are used in a private fashion. 

What do we feel about making these changes?

**Comment by mcmire** [comment]
Got it. Would you be opposed to me creating a PR, at least, to exclude test files from JSDoc?

**Comment by Gudahtt** [comment]
This config doesn't actually dictate _where_ the rules are used. We provide a base config and extended configs for use with specific tools. But disabling rules for tests in particular might have to go in the root ESLint config for each project.

**Comment by mcmire** [comment]
Ah ok! That makes sense. Thanks for the explanation!
