### ISSUE TITLE
Update to ESLint 7

### ISSUE THREAD

**Issue by whymarrh** [MetaMask/eslint-config#46]
As of #45, we're suggesting `eslint@6`. We'll need to update the rules and packages for [ESLint 7](https://eslint.org/docs/user-guide/migrating-to-7.0.0).

Tasks:

- [x] Update docs (#63)
- [x] Update rules (#58)
- [x] Update packages (#62)

**Comment by whymarrh** [comment]
> * Update packages

- [x] `eslint-plugin-import` is compatible with ESLint `^7.2.0`
- [x] `eslint-plugin-jest` is compatible with `>=5`
- [x] `eslint-plugin-mocha` (#59)
- [x] `eslint-plugin-node` is compatible with `>=5.16.0`

**Comment by Gudahtt** [comment]
This was done in #62, along with some related work in various other PRs.
