### ISSUE TITLE
Omit ES2018+ specific rules from base config

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/eslint-config#50]
Rules such as `prefer-object-spread` that refer to ES2018+ syntax should not be included in the base config, as not all of our modules support ES2018. Our minimum extension browser versions only support up to ES2017.

**Comment by whymarrh** [comment]
Are there other rules that we should disable? From a quick look it might be just the one.

**Comment by Gudahtt** [comment]
That's the only one I found
