### ISSUE TITLE
Use prettier

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/eslint-config#91]
We should use prettier by default, straight in the `index.js` config.

**Comment by brad-decker** [comment]
If possible, lets enable semicolons as a part of this change. I do believe that the lack of semi-colons is causing Prettier's parsing to be significantly slower than what it could be.

**Comment by brad-decker** [comment]
Proposal: This should be added to the base config after we land the #140 PR

**Comment by rekmarks** [comment]
We did it! 😄
